# Generated by Django 5.2.17 on 2026-09-16 17:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('scenario', models.TextField(blank=True, null=True)),
                ('key_points', models.JSONField(blank=True, default=list)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('difficulty_rating', models.IntegerField()),
                ('probe', models.CharField(choices=[('none', 'None'), ('above', 'One level above'), ('below', 'One level below')], default='none', max_length=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='active', max_length=10)),
                ('source', models.CharField(choices=[('generated', 'Generated'), ('manual', 'Manual')], default='generated', max_length=10)),
                ('generation_model', models.CharField(blank=True, max_length=80)),
                ('prompt_version', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('generation_hint', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
