# Generated by Django 5.2.17 on 2026-09-16 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('practice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created_in_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cards', to='practice.dailysession'),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.category'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('slug',), name='uniq_global_category_slug'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='uniq_personal_category_slug'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['user', 'status'], name='cards_card_user_id_698812_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['user', 'category'], name='cards_card_user_id_83f60b_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['user', 'cefr_level'], name='cards_card_user_id_823179_idx'),
        ),
    ]
