# Generated by Django 5.2.17 on 2026-09-22 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_seed_global_categories'),
        ('practice', '0002_sessionlanguageplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French (Canada)')], default='en', max_length=8),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['user', 'language'], name='cards_card_user_id_cdd3ea_idx'),
        ),
    ]
