# Generated by Django 5.2.17 on 2026-09-23 21:19

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='question_audio',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.core.storage.card_audio_path),
        ),
        migrations.AddField(
            model_name='card',
            name='question_audio_model',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='card',
            name='question_audio_seconds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='question_audio_voice',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
