# Generated by Django 5.2.17 on 2026-09-16 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0002_initial'),
        ('practice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logged_on', models.DateField()),
                ('rating_before', models.IntegerField()),
                ('rating_after', models.IntegerField()),
                ('delta', models.IntegerField()),
                ('question_rating', models.IntegerField()),
                ('expected', models.DecimalField(decimal_places=3, max_digits=4)),
                ('actual', models.DecimalField(decimal_places=3, max_digits=4)),
                ('k_factor', models.PositiveSmallIntegerField()),
                ('level_version', models.CharField(max_length=20)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level_change', to='practice.attempt')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_logs', to='cards.card')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_on', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'logged_on'], name='leveling_le_user_id_2e4ff2_idx')],
            },
        ),
    ]
