# Generated by Django 5.2.17 on 2026-09-22 23:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_language'),
        ('leveling', '0001_initial'),
        ('practice', '0002_sessionlanguageplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='levellog',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French (Canada)')], default='en', max_length=8),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='levellog',
            index=models.Index(fields=['user', 'language', 'logged_on'], name='leveling_le_user_id_4f7690_idx'),
        ),
    ]
