# Generated by Django 5.2.17 on 2026-09-16 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('generate_questions', 'Generate questions'), ('transcribe', 'Transcribe'), ('evaluate', 'Evaluate'), ('improve_answer', 'Improve answer')], max_length=20)),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=80)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cache_read_input_tokens', models.PositiveIntegerField(default=0)),
                ('cache_creation_input_tokens', models.PositiveIntegerField(default=0)),
                ('audio_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], max_length=8)),
                ('error', models.TextField(blank=True)),
                ('related_object_type', models.CharField(blank=True, max_length=40)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_aireques_user_id_0890a7_idx'), models.Index(fields=['kind'], name='ai_aireques_kind_381231_idx')],
            },
        ),
    ]
