# Generated by Django 5.2.17 on 2026-09-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequestlog',
            name='language',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
