# Generated by Django 5.2.17 on 2026-09-23 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_airequestlog_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airequestlog',
            name='key_source',
            field=models.CharField(choices=[('user', "User's own key"), ('global', 'Global key')], default='global', max_length=8),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='kind',
            field=models.CharField(choices=[('generate_questions', 'Generate questions'), ('transcribe', 'Transcribe'), ('evaluate', 'Evaluate'), ('improve_answer', 'Improve answer'), ('tts', 'Text to speech')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='airequestlog',
            index=models.Index(fields=['user', 'key_source'], name='ai_aireques_user_id_c7b107_idx'),
        ),
    ]
