# Generated by Django 5.2.17 on 2026-09-16 17:21

import apps.accounts.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=64, validators=[apps.accounts.models.validate_timezone])),
                ('feedback_language', models.CharField(choices=[('pt-BR', 'Português (Brasil)'), ('en', 'English')], default='pt-BR', max_length=8)),
                ('default_new_cards_per_day', models.PositiveSmallIntegerField(default=3)),
                ('level_rating', models.IntegerField(default=apps.accounts.models.default_initial_rating)),
                ('level_rating_initial', models.IntegerField(blank=True, null=True)),
                ('counted_attempts', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
