# Generated by Django 5.2.17 on 2026-09-22 23:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French (Canada)')], max_length=8)),
                ('level_rating', models.IntegerField()),
                ('level_rating_initial', models.IntegerField()),
                ('counted_attempts', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('default_new_cards_per_day', models.PositiveSmallIntegerField(default=3)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['activated_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('user', 'language'), name='uniq_language_profile')],
            },
        ),
    ]
