# Generated by Django 5.2.17 on 2026-09-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_backfill_en_language_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='counted_attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_new_cards_per_day',
        ),
        migrations.RemoveField(
            model_name='user',
            name='level_rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='level_rating_initial',
        ),
    ]
