# Generated by Django 5.2.17 on 2026-09-23 21:18

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_level_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anthropic_api_key',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='anthropic_api_key_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='openai_api_key',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='openai_api_key_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='question_mode',
            field=models.CharField(choices=[('read', 'Read'), ('listen', 'Listen'), ('both', 'Read and listen')], default='read', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='show_thinking_timer',
            field=models.BooleanField(default=True),
        ),
    ]
