# Generated by Django 5.2.17 on 2026-09-16 17:21

import apps.core.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField()),
                ('new_cards_target', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='generating', max_length=12)),
                ('generation_error', models.TextField(blank=True)),
                ('rating_at_start', models.IntegerField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='sessions', to='cards.category')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('attempted_on', models.DateField()),
                ('counts_for_scheduling', models.BooleanField(default=False)),
                ('insufficient_speech', models.BooleanField(default=False)),
                ('audio_file', models.FileField(max_length=255, upload_to=apps.core.storage.attempt_audio_path)),
                ('audio_mime', models.CharField(max_length=100)),
                ('audio_size_bytes', models.PositiveIntegerField(default=0)),
                ('client_duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('audio_duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('probing', 'Probing audio'), ('transcribing', 'Transcribing'), ('evaluating', 'Evaluating'), ('scheduling', 'Scheduling'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=14)),
                ('failure_stage', models.CharField(blank=True, max_length=14)),
                ('error_message', models.TextField(blank=True)),
                ('transcript_text', models.TextField(blank=True)),
                ('transcript_segments', models.JSONField(blank=True, default=list)),
                ('word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('words_per_minute', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('transcription_model', models.CharField(blank=True, max_length=60)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='cards.card')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='practice.dailysession')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('structure_score', models.PositiveSmallIntegerField()),
                ('grammar_score', models.PositiveSmallIntegerField()),
                ('fluency_score', models.PositiveSmallIntegerField()),
                ('structure_feedback', models.TextField(blank=True)),
                ('grammar_feedback', models.TextField(blank=True)),
                ('fluency_feedback', models.TextField(blank=True)),
                ('grammar_issues', models.JSONField(blank=True, default=list)),
                ('fluency_markers', models.JSONField(blank=True, default=dict)),
                ('composite_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sm2_quality', models.PositiveSmallIntegerField()),
                ('improved_answer', models.TextField(blank=True, null=True)),
                ('improved_answer_notes', models.JSONField(blank=True, default=list)),
                ('improved_answer_model', models.CharField(blank=True, max_length=80)),
                ('improved_answer_generated_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.CharField(max_length=80)),
                ('prompt_version', models.CharField(max_length=20)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='practice.attempt')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionNewCard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('origin', models.CharField(choices=[('generated', 'Generated'), ('carried_over', 'Carried over')], max_length=12)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_slots', to='cards.card')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_cards', to='practice.dailysession')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='dailysession',
            constraint=models.UniqueConstraint(fields=('user', 'session_date'), name='uniq_session_per_day'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'attempted_on'], name='practice_at_user_id_56deec_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'status'], name='practice_at_user_id_c0e1e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('user', 'card', 'attempt_number'), name='uniq_card_attempt_no'),
        ),
        migrations.AddConstraint(
            model_name='sessionnewcard',
            constraint=models.UniqueConstraint(fields=('user', 'session', 'card'), name='uniq_session_card'),
        ),
    ]
