# Generated by Django 5.2.17 on 2026-09-22 23:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLanguagePlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French (Canada)')], max_length=8)),
                ('new_cards_target', models.PositiveSmallIntegerField()),
                ('rating_at_start', models.IntegerField()),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=8)),
                ('generation_error', models.TextField(blank=True)),
                ('generated_count', models.PositiveSmallIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='practice.dailysession')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['language'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('user', 'session', 'language'), name='uniq_session_language_plan')],
            },
        ),
    ]
