# Generated by Django 5.2.17 on 2026-09-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_backfill_session_plans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysession',
            name='new_cards_target',
        ),
        migrations.RemoveField(
            model_name='dailysession',
            name='rating_at_start',
        ),
    ]
