# Generated by Django 5.2.17 on 2026-09-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_remove_dailysession_target_and_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='audio_replays',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='question_mode',
            field=models.CharField(blank=True, choices=[('read', 'Read'), ('listen', 'Listen'), ('both', 'Read and listen')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='text_revealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attempt',
            name='thinking_baseline_seconds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='thinking_seconds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
