# Generated by Django 5.2.17 on 2026-09-16 17:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('practice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewed_on', models.DateField()),
                ('quality', models.PositiveSmallIntegerField()),
                ('composite_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ease_before', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ease_after', models.DecimalField(decimal_places=2, max_digits=4)),
                ('interval_before', models.PositiveIntegerField()),
                ('interval_after', models.PositiveIntegerField()),
                ('due_before', models.DateField(blank=True, null=True)),
                ('due_after', models.DateField()),
                ('maturity_before', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('mature', 'Mature')], max_length=10)),
                ('maturity_after', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('mature', 'Mature')], max_length=10)),
                ('scheduler_version', models.CharField(max_length=20)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='practice.attempt')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='cards.card')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_on', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'reviewed_on'], name='scheduling__user_id_5afee0_idx')],
            },
        ),
        migrations.CreateModel(
            name='SchedulerState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maturity', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('mature', 'Mature')], default='new', max_length=10)),
                ('ease_factor', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=4)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('last_reviewed_on', models.DateField(blank=True, null=True)),
                ('last_quality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduler', to='cards.card')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'due_date'], name='scheduling__user_id_46963f_idx'), models.Index(fields=['user', 'maturity'], name='scheduling__user_id_23cd5d_idx')],
            },
        ),
    ]
